apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despachos
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-despachos
  template:
    metadata:
      labels:
        app: backend-despachos
    spec:
      containers:
      - name: backend-despachos
        # Reemplaza 921558516087 por tu ID de cuenta si es diferente
        image: 921558516087.dkr.ecr.us-east-1.amazonaws.com/backend-despachos:latest
        ports:
        - containerPort: 8081
        env:
        - name: DB_ENDPOINT
          value: "TU-ENDPOINT-DE-RDS-AQUI" # <-- LUEGO PONDREMOS TU BASE DE DATOS
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "despachos_db"
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "tu_password_rds"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-despachos-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: backend-despachos
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
