apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-despachos-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-despachos-db
  template:
    metadata:
      labels:
        app: mysql-despachos-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        # Forzamos el método de autenticación clásico compatible con drivers de Java
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin123"
        - name: MYSQL_DATABASE
          value: "despachos_db"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-despachos-service
  namespace: default
spec:
  selector:
    app: mysql-despachos-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despachos
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-despachos
  template:
    metadata:
      labels:
        app: backend-despachos
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z -w 2 mysql-despachos-service 3306; do echo "Esperando a MySQL..."; sleep 2; done;']
      containers:
      - name: backend-despachos
        image: 921558516087.dkr.ecr.us-east-1.amazonaws.com/backend-despachos:latest
        ports:
        - containerPort: 8081
        env:
        # 1. Variables de entorno personalizadas (Por si el código las busca explícitamente)
        - name: DB_ENDPOINT
          value: "mysql-despachos-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "despachos_db"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "admin123"
        # 2. Variables de entorno estándar de Spring (Agregamos allowPublicKeyRetrieval para MySQL 8)
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-despachos-service:3306/despachos_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "admin123"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: RESTART_VERSION
          value: "12"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-despachos-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: backend-despachos
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
